<a href="https://colab.research.google.com/github/vaseemdane/Guess-the-secrete-number/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import random

In [10]:
np_array=np.array([(1,2,3,4,5),(5,4,3,2,1)])


In [11]:
np_array

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [12]:
np_array.shape

(2, 5)

In [13]:
a=np.zeros((3,3))

In [14]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
a[0,0]=12
a

array([[12.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [21]:
b=np.ones((4,4))
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
c=np.full((4,4),2)
c

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [26]:
d=np.eye(5)
d

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
e=np.random.random((3,4))
e

array([[0.16557477, 0.31789355, 0.77782273, 0.28026659],
       [0.7277976 , 0.16240551, 0.35778586, 0.60884371],
       [0.66916377, 0.23262124, 0.3034187 , 0.80534828]])

In [29]:
a=np.random.randint(1,20,(3,4))
a

array([[ 5,  7,  5, 16],
       [16,  5, 11,  1],
       [13, 12,  3, 12]])

In [36]:
a=np.linspace(10,30,10)
a

array([10.        , 12.22222222, 14.44444444, 16.66666667, 18.88888889,
       21.11111111, 23.33333333, 25.55555556, 27.77777778, 30.        ])

In [38]:
 r=np.arange(10,31,8)
 r

array([10, 18, 26])

In [41]:
list=[1,2,3,4,5]
np_array=np.asarray(list)
np_array

array([1, 2, 3, 4, 5])

In [44]:
a=np.random.randint(10,30,(4,4))
b=np.random.randint(40,60,(4,4))
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(a.T)

[[62 52 81 72]
 [76 80 56 56]
 [57 55 76 54]
 [76 69 63 65]]
[[-34 -28 -23 -46]
 [-30 -36 -34 -30]
 [-23 -35 -26 -28]
 [-26 -17 -31 -25]]
[[ 672  480 1508  767]
 [1219 1276  495  559]
 [ 680  450 1275  533]
 [1275 1118  752  900]]
[[0.29166667 0.3        0.55769231 0.22033898]
 [0.43396226 0.37931034 0.24444444 0.30232558]
 [0.425      0.22222222 0.49019608 0.31707317]
 [0.49019608 0.60465116 0.34042553 0.44444444]]
[[14 23 17 25]
 [12 22 10 26]
 [29 11 25 16]
 [13 13 13 20]]
